version: "2.29"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
    depends_on:
      - php
      - pgsql
  php:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    links:
      - pgsql
    volumes:
      - ./src:/var/www/laravel:rw
    user:
      "www-data"
  pgsql:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: laravel_db
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres:/data/postgres:rw
  composer:
    build: 
      context: dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/laravel:rw
  
  artisan:
    build: 
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php","/var/www/laravel/artisan"]

  node:
    build:
      context: dockerfiles
      dockerfile: node.dockerfile
    volumes:
      - ./src:/var/www/laravel
  